name: integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * *'

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        check: [pylint]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tox
    - name: Run checks with tox
      run: |
        tox -e ${{ matrix.check }}

  tests:
    needs: checks
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -e py

      - name: Test with tox and Cython
        run: tox -e py-cython

  builds:
    needs: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_TEST_REQUIRES: pytest pytest-cov pytest-xdist
          CIBW_TEST_COMMAND: pytest -c {project} {project}/tests
          CIBW_SKIP: pp*
