name: release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_TEST_REQUIRES: pytest pytest-cov pytest-xdist
          CIBW_TEST_COMMAND: pytest -c {project} {project}/tests
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

  upload:
    needs: builds
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create source dist
      run: python setup.py sdist

    - name: Stage wheels
      uses: actions/download-artifact@v3
      with:
        name: wheelhouse
        path: wheelhouse
    - run: |
        mv -v wheelhouse/* dist/
        ls dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
